### ISSUE TITLE
Fees - Suggestion

### ISSUE THREAD

**Issue by criptonauta** [BenjiLee/PoloniexAnalyzer#17]
Hey Benji

Could we have a sum of all fees converted to BTC in the last line? That would be awesome.

Thanks for the great work.

Regards

Criptonauta

**Comment by BenjiLee** [comment]
@criptonauta I will see what I can do. Also. I love manatees.

**Comment by BenjiLee** [comment]
@criptonauta Suggestion implemented in https://github.com/BenjiLee/PoloniexAnalyzer/pull/25

Thank you for you suggestion!

**Comment by criptonauta** [comment]
Hi Benji!
Got an error

ETH_REP=0.0055
BTC_BITS=0.007
BTC_NSR=0.004
-------------Total Fees-------------
Traceback (most recent call last):
  File "poloniex.py", line 64, in <module>
    main()
  File "poloniex.py", line 56, in main
    actions[args.action]['function']()
  File "D:\POLO\ash\new\analyzer.py", line 122, in calculate_fees
    total_fees += float(all_prices["BTC_" + currency]['last']) * fees
KeyError: u'BTC_USDT'

Saludos cordiales

**Comment by criptonauta** [comment]
And this with another API

$ python poloniex.py -a CalculateFees
--------------All Fees--------------
BTC_NXC=0.007
BTC_BBR=0.0075
BTC_XRP=0.0285
BTC_XMR=0.027
BTC_DASH=0.0695
BTC_XEM=0.0125
BTC_EMC2=0.024
BTC_MAID=0.057
BTC_ARDR=0.014
BTC_GNT=0.1225
BTC_STEEM=0.0105
BTC_REP=0.0215
BTC_FLDC=0.008
BTC_ETC=0.036
BTC_ETH=0.053
BTC_FCT=0.0425
BTC_PPC=0.004
BTC_STRAT=0.0125
BTC_LSK=0.0045
BTC_POT=0.016
BTC_BITS=0.026
BTC_LBC=0.0305
BTC_DCR=0.0155
ETH_REP=0.0015
-------------Total Fees-------------
Total fees in BTC=0.650062547015

It couldn't be 0.6 in taxes because this account have about 14 dollars ^^

**Comment by BenjiLee** [comment]
> KeyError: u'BTC_USDT'

Not sure why the Tether is having an issue.

> It couldn't be 0.6 in taxes because this account have about 14 dollars ^^

You would be surprised how much Poloniex makes off your trades! This is one of the reasons why I added the fees calculator in the first place. 

Edit:
Turns out USDT is the only exception when calculating total in BTC

Fix made here https://github.com/BenjiLee/PoloniexAnalyzer/pull/27

**Comment by criptonauta** [comment]
Thanks for the fix!

But regarding the zeroes, look this api. I have ~2BTC on it

but the fees, astronomical!

-------------Total Fees-------------
Total fees in BTC=58.3745413272
