### ISSUE TITLE
Font coding

### ISSUE THREAD

**Issue by criptonauta** [BenjiLee/PoloniexAnalyzer#18]
What is the correct font coding for Brazilian Portuguese?

I'm using 
```
#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
```
But the result is being this:

 GetChangeOverTime
        Fun├º├úo p├║blica: Retorna a mudan├ºa da porcentagem em uma s├®rie de
        per├¡odos de tempo para moedas que excedam um volume m├¡nimo

All accents like é, á, â, etc are becoming Ansii...

latin-1 is also not working.

Best regards!

**Comment by BenjiLee** [comment]
Not sure how to do it with `# -*- coding: ISO-8859-1 -*-` but another way to type those characters is to use unicode. 

I'm not too knowledge in the subject but here is a nice tutorial about it https://nedbatchelder.com/text/unipain.html

Closing this issue as it is unrelated to the repo.
