### ISSUE TITLE
Unit testing?

### ISSUE THREAD

**Issue by cyrusv** [BenjiLee/PoloniexAnalyzer#21]
Are there unit tests?

**Comment by BenjiLee** [comment]
There should be... but I'm a horrible person. I think the way I have currently coded everything is going to be changed so I was waiting until I was happy with the architecture (or lack of) before adding unit tests.

**Comment by cyrusv** [comment]
It looks like this won't be prioritized, closing the request

**Comment by BenjiLee** [comment]
lol
