### ISSUE TITLE
You invested (negative BTC value)

### ISSUE THREAD

**Issue by fhdummy** [BenjiLee/PoloniexAnalyzer#34]
Hello,

when I start the program with the command `poloniex.py -a GetDetailedOverview` I get several outputs that list a negative BTC value at the line "You invested ...", see the following example:

```
--------------BTC_GNT----------------
You invested -0.6760799618 BTC for 6752.17666661 GNT/1.08547992092 BTC
If you sold it all at the current price (assuming enough sell orders)

1.76155988272 BTC/2898.0 USD
```

How can that be? 

Thanks.

**Comment by BenjiLee** [comment]
1.76155988272  - 1.08547992092 = 0.6760799618 

It means you've already made 0.6760799618 BTC from GNT but still have a balance of 6752.17666661 GNT/1.08547992092 BTC which totals to 1.76155988272 BTC/2898.0 USD

Another way to look at it. You have 1.08547992092 BTC worth of GNT right now. You've spent -0.6760799618 BTC to get this. 

An oversimplfied example:
```
You invested -1 BTC for 10 BTC
If you sold it all at the current price (assuming enough sell orders)

11 BTC
```
Would it be helpful if I added "Total earnings" for the value of last line?

**Comment by fhdummy** [comment]
Thanks for the clarifying answer.

No, I don't think "Total earnings" would make the output, that contains the negative BTC value, more clear. The output "If you sold it all at the current price (assuming enough sell orders) ..." is fine in my opinion.

You could, however, add a hint somewhere, that explains what it means, when the value "You invested ..." is negative.

**Comment by BenjiLee** [comment]
I'll keep this ticket open until I can think of a good way to display this piece of information. Some thoughts include:
* Add more clarifying text inline
* Add more clarifying text at the top
* Change the format of the sentence depending on if it's negative

**Comment by BenjiLee** [comment]
Let's try this for now https://github.com/BenjiLee/PoloniexAnalyzer/pull/38
