### ISSUE TITLE
error

### ISSUE THREAD

**Issue by saine22** [BenjiLee/PoloniexAnalyzer#49]
![image](https://user-images.githubusercontent.com/29252993/27388520-68859a66-56a4-11e7-9550-ce6eea51208c.png)
how to fix ?
![image](https://user-images.githubusercontent.com/29252993/27388567-87af8a5a-56a4-11e7-9959-04a3da6045e8.png)
![image](https://user-images.githubusercontent.com/29252993/27388632-b62f3128-56a4-11e7-8665-1ffdc29091e3.png)

**Comment by BenjiLee** [comment]
@saine22 Thanks for  reporting this. An proposed fix is in https://github.com/BenjiLee/PoloniexAnalyzer/pull/50
