### ISSUE TITLE
Fees

### ISSUE THREAD

**Issue by stitrace** [BenjiLee/PoloniexAnalyzer#51]
What does yhat mean?

python3 poloniex.py -a CalculateFees
--------------All Fees--------------
USDT_BTC=5.193500000000116
-------------Total Fees-------------
Total fees in BTC=13684.872500000305

**Comment by BenjiLee** [comment]
Thanks for the issue report!
Fixed in https://github.com/BenjiLee/PoloniexAnalyzer/pull/52
