### ISSUE TITLE
name 'current' is not defined

### ISSUE THREAD

**Issue by stitrace** [BenjiLee/PoloniexAnalyzer#53]
If USDT/BTC trades only in history.

python3 poloniex.py -a GetDetailedOverview
Warning! If you made non BTC trades, for example, ETH to ETC, some
of the values may look unusual. Since non BTC trades have not been
calculated in.
Traceback (most recent call last):
  File "poloniex.py", line 73, in <module>
    main()
  File "poloniex.py", line 65, in main
    actions[args.action]['function']()
  File "/home/stitrace/PoloniexAnalyzer/analyzer.py", line 86, in get_detailed_overview
    return current
NameError: name 'current' is not defined

**Comment by BenjiLee** [comment]
@stitrace I haven't calculated in trades where BTC is the base coin. USDT/BTC uses USDT as the base coin so there would be no results. The error you see is actually at the end of the analysis so it doesn't mean much.

Hang tight. Looking at issues to tackle to today. This is up next.

**Comment by BenjiLee** [comment]
@stitrace 
Hopefully fixed in https://github.com/BenjiLee/PoloniexAnalyzer/pull/54
