### ISSUE TITLE
CalculateFees exception

### ISSUE THREAD

**Issue by stitrace** [BenjiLee/PoloniexAnalyzer#57]
poloniex.py -a CalculateFees
Traceback (most recent call last):
  File "poloniex.py", line 73, in <module>
    main()
  File "poloniex.py", line 65, in main
    actions[args.action]['function']()
  File "/home/stitrace/PoloniexAnalyzer/analyzer.py", line 85, in calculate_fees
    trade_history = TradeHistory(trading_api.return_trade_history())
TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by BenjiLee** [comment]
Sounds like I need some tests >.<

I'll take a look at this later today

**Comment by BenjiLee** [comment]
Should be fixed in https://github.com/BenjiLee/PoloniexAnalyzer/pull/58

**Comment by stitrace** [comment]
Ok, it's worked now. Thanks.
